# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.positions_response import PositionsResponse

class TestPositionsResponse(unittest.TestCase):
    """PositionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PositionsResponse:
        """Test PositionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PositionsResponse`
        """
        model = PositionsResponse()
        if include_optional:
            return PositionsResponse(
                s = 'ok',
                d = [
                    openapi_client.models.position_record.PositionRecord(
                        sym_id = '', 
                        product = 'delivery', 
                        buy_qty = 1.337, 
                        buy_value = 1.337, 
                        buy_avg_price = 1.337, 
                        sell_qty = 1.337, 
                        sell_value = 1.337, 
                        sell_avg_price = 1.337, 
                        cf_qty = 1.337, 
                        cf_value = 1.337, 
                        cf_avg_price = 1.337, 
                        net_qty = 1.337, 
                        net_avg_price = 1.337, 
                        net_value = 1.337, 
                        realized_pnl = 1.337, 
                        price_factor = 1.337, 
                        multiplier = 1.337, 
                        sym = {
                            'key' : None
                            }, 
                        cf_org_avg_price = 1.337, 
                        cf_org_value = 1.337, 
                        net_org_avg_price = 1.337, 
                        net_org_value = 1.337, 
                        realized_org_pnl = 1.337, 
                        day_pos = openapi_client.models.day_position.DayPosition(
                            day_qty = 1.337, 
                            day_avg = 1.337, 
                            day_realized_pnl = 1.337, 
                            day_net_value = 1.337, 
                            convert_pos = True, 
                            day_premium = 1.337, ), 
                        convert_pos = True, 
                        net_premium = 1.337, 
                        trans_history = True, 
                        create_tsl = True, )
                    ]
            )
        else:
            return PositionsResponse(
        )
        """

    def testPositionsResponse(self):
        """Test PositionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
