# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.pending_gtt_orders200_response import PendingGTTOrders200Response

class TestPendingGTTOrders200Response(unittest.TestCase):
    """PendingGTTOrders200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PendingGTTOrders200Response:
        """Test PendingGTTOrders200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PendingGTTOrders200Response`
        """
        model = PendingGTTOrders200Response()
        if include_optional:
            return PendingGTTOrders200Response(
                s = '',
                d = [
                    openapi_client.models.pending_gtt_order_data.PendingGTTOrderData(
                        sym_id = '', 
                        exchange = '', 
                        order_id = '', 
                        side = '', 
                        trigger_type = 'Single', 
                        single = openapi_client.models.place_order_params_data.PlaceOrderParamsData(
                            remarks = '', 
                            trig_price = 1.337, 
                            product = 'delivery', 
                            type = 'limit', 
                            qty = 1.337, 
                            price = 1.337, ), 
                        stop_loss = openapi_client.models.place_order_params_data.PlaceOrderParamsData(
                            remarks = '', 
                            trig_price = 1.337, 
                            product = 'delivery', 
                            type = 'limit', 
                            qty = 1.337, 
                            price = 1.337, ), 
                        target = , )
                    ],
                msg = ''
            )
        else:
            return PendingGTTOrders200Response(
        )
        """

    def testPendingGTTOrders200Response(self):
        """Test PendingGTTOrders200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
