# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_logout_web_response(self) -> None:
        """Test case for get_logout_web_response

        Logout
        """
        pass

    def test_get_user_details(self) -> None:
        """Test case for get_user_details

        Details
        """
        pass


if __name__ == '__main__':
    unittest.main()
