# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_order(self) -> None:
        """Test case for cancel_order

        Cancel Order
        """
        pass

    def test_convert_position(self) -> None:
        """Test case for convert_position

        Convert Position 
        """
        pass

    def test_get_basket_order_margin(self) -> None:
        """Test case for get_basket_order_margin

        Basket Order Margin
        """
        pass

    def test_get_holdings(self) -> None:
        """Test case for get_holdings

        Holdings 
        """
        pass

    def test_get_order_history(self) -> None:
        """Test case for get_order_history

        History
        """
        pass

    def test_get_order_margin(self) -> None:
        """Test case for get_order_margin

        Order Margin
        """
        pass

    def test_get_orders(self) -> None:
        """Test case for get_orders

        Orders
        """
        pass

    def test_get_positions(self) -> None:
        """Test case for get_positions

        Positions 
        """
        pass

    def test_get_trades(self) -> None:
        """Test case for get_trades

        Trades
        """
        pass

    def test_modify_order(self) -> None:
        """Test case for modify_order

        Modify Order
        """
        pass

    def test_place_order(self) -> None:
        """Test case for place_order

        Place Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
