# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.order_margin_response import OrderMarginResponse

class TestOrderMarginResponse(unittest.TestCase):
    """OrderMarginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderMarginResponse:
        """Test OrderMarginResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderMarginResponse`
        """
        model = OrderMarginResponse()
        if include_optional:
            return OrderMarginResponse(
                s = 'ok',
                d = openapi_client.models.order_margin_data.OrderMarginData(
                    available_margin = 1.337, 
                    required_margin = 1.337, 
                    shortfall = 1.337, 
                    hold_qty = 1.337, 
                    remarks = '', 
                    edis_auth_required = True, )
            )
        else:
            return OrderMarginResponse(
        )
        """

    def testOrderMarginResponse(self):
        """Test OrderMarginResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
