# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.security_info import SecurityInfo

class TestSecurityInfo(unittest.TestCase):
    """SecurityInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityInfo:
        """Test SecurityInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityInfo`
        """
        model = SecurityInfo()
        if include_optional:
            return SecurityInfo(
                symbol = '',
                segment = '',
                expiry = '',
                instrument = '',
                tick_size = '',
                lot_size = '',
                multiplier = '',
                gn_gd_bypn_pd = '',
                price_unit = '',
                price_quote_qty = '',
                trade_unit = '',
                delivery_unit = '',
                freeze_qty = '',
                additional_long_mgn = '',
                additional_short_mgn = '',
                exercise_start_date = '',
                exercise_end_date = '',
                tender_start_date = '',
                tender_end_date = '',
                elm_buy_mgn = '',
                elm_start_mgn = '',
                special_long_mgn = '',
                special_short_mgn = '',
                contract_token = ''
            )
        else:
            return SecurityInfo(
        )
        """

    def testSecurityInfo(self):
        """Test SecurityInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
