# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.advance_orders_api import AdvanceOrdersApi


class TestAdvanceOrdersApi(unittest.TestCase):
    """AdvanceOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdvanceOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_gtt_order(self) -> None:
        """Test case for cancel_gtt_order

        Cancel GTT Order
        """
        pass

    def test_cancel_oco_order(self) -> None:
        """Test case for cancel_oco_order

        Cancel OCO Order
        """
        pass

    def test_exit_order(self) -> None:
        """Test case for exit_order

        Exit Order
        """
        pass

    def test_modify_bracket_order(self) -> None:
        """Test case for modify_bracket_order

        Modify Bracket Order
        """
        pass

    def test_modify_cover_order(self) -> None:
        """Test case for modify_cover_order

        Modify Cover Order
        """
        pass

    def test_modify_gtt_order(self) -> None:
        """Test case for modify_gtt_order

        Modify GTT Order
        """
        pass

    def test_modify_oco_order(self) -> None:
        """Test case for modify_oco_order

        Modify OCO Order
        """
        pass

    def test_pending_gtt_orders(self) -> None:
        """Test case for pending_gtt_orders

        GTT OrderBook
        """
        pass

    def test_place_bracket_order(self) -> None:
        """Test case for place_bracket_order

        Place Bracket Order
        """
        pass

    def test_place_cover_order(self) -> None:
        """Test case for place_cover_order

        Place Cover Order
        """
        pass

    def test_place_gtt_order(self) -> None:
        """Test case for place_gtt_order

        Place GTT Order
        """
        pass

    def test_place_oco_order(self) -> None:
        """Test case for place_oco_order

        Place OCO Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
