# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.index_constituent import IndexConstituent

class TestIndexConstituent(unittest.TestCase):
    """IndexConstituent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndexConstituent:
        """Test IndexConstituent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndexConstituent`
        """
        model = IndexConstituent()
        if include_optional:
            return IndexConstituent(
                constituents = [
                    openapi_client.models.constituent_data.ConstituentData(
                        id = '', 
                        change_per = 1.337, 
                        weightage = 1.337, 
                        contribution_point = 1.337, )
                    ],
                gainer_count = 56,
                loser_count = 56,
                normal_count = 56
            )
        else:
            return IndexConstituent(
        )
        """

    def testIndexConstituent(self):
        """Test IndexConstituent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
