# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.modify_gtt_order_response import ModifyGTTOrderResponse

class TestModifyGTTOrderResponse(unittest.TestCase):
    """ModifyGTTOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModifyGTTOrderResponse:
        """Test ModifyGTTOrderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModifyGTTOrderResponse`
        """
        model = ModifyGTTOrderResponse()
        if include_optional:
            return ModifyGTTOrderResponse(
                s = 'ok',
                d = openapi_client.models.modify_gtt_order_data.ModifyGTTOrderData(
                    msg = '', 
                    order_id = '', )
            )
        else:
            return ModifyGTTOrderResponse(
        )
        """

    def testModifyGTTOrderResponse(self):
        """Test ModifyGTTOrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
