# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.limits_response import LimitsResponse

class TestLimitsResponse(unittest.TestCase):
    """LimitsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LimitsResponse:
        """Test LimitsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LimitsResponse`
        """
        model = LimitsResponse()
        if include_optional:
            return LimitsResponse(
                s = 'ok',
                d = openapi_client.models.limit_data.LimitData(
                    total_credits = 1.337, 
                    avail_margin = 1.337, 
                    brokerage = 1.337, 
                    avail_cash = 1.337, 
                    peak_margin = 1.337, 
                    pay_in = 1.337, 
                    span = 1.337, 
                    realized_pnl = 1.337, 
                    unrealized_pn_l = 1.337, 
                    exposure = 1.337, 
                    ad_hoc_margin = 1.337, 
                    stock_collateral = 1.337, 
                    option_premium = 1.337, 
                    segment = '', 
                    pay_out = 1.337, 
                    brk_collat_amount = 1.337, 
                    uncleared_cash = 1.337, 
                    aux_cash = 1.337, 
                    aux_collat_amount = 1.337, 
                    aux_uncleared_cash = 1.337, 
                    day_cash = 1.337, 
                    turn_over_lmt = 1.337, 
                    pend_ord_val_lmt = 1.337, 
                    turnover = 1.337, 
                    pend_ord_value = 1.337, 
                    margin_used = 1.337, 
                    premium = 1.337, 
                    brokerage_derivatives_bo = 1.337, 
                    brokerage_derivatives_margin = 1.337, 
                    opt_premium_der_marg = 1.337, )
            )
        else:
            return LimitsResponse(
        )
        """

    def testLimitsResponse(self):
        """Test LimitsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
