# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.iou_response_scrip_version_info import IouResponseScripVersionInfo

class TestIouResponseScripVersionInfo(unittest.TestCase):
    """IouResponseScripVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IouResponseScripVersionInfo:
        """Test IouResponseScripVersionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IouResponseScripVersionInfo`
        """
        model = IouResponseScripVersionInfo()
        if include_optional:
            return IouResponseScripVersionInfo(
                s = 'ok',
                d = openapi_client.models.scrip_version_info.ScripVersionInfo(
                    version = 56, 
                    updated = True, 
                    symbol_store = [
                        openapi_client.models.symbol_store_data.SymbolStoreData(
                            name = '', 
                            sort_order = 56, 
                            id_format = '', 
                            data = '', 
                            build_version = [
                                ''
                                ], 
                            append = openapi_client.models.symbol_store_appender.SymbolStoreAppender(
                                data = '', ), )
                        ], )
            )
        else:
            return IouResponseScripVersionInfo(
        )
        """

    def testIouResponseScripVersionInfo(self):
        """Test IouResponseScripVersionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
