# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_basket_order_margin200_response import GetBasketOrderMargin200Response

class TestGetBasketOrderMargin200Response(unittest.TestCase):
    """GetBasketOrderMargin200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBasketOrderMargin200Response:
        """Test GetBasketOrderMargin200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBasketOrderMargin200Response`
        """
        model = GetBasketOrderMargin200Response()
        if include_optional:
            return GetBasketOrderMargin200Response(
                s = '',
                d = openapi_client.models.basket_order_margin_data.BasketOrderMarginData(
                    required_margin = 1.337, 
                    final_margin = 1.337, 
                    existing_margin_used = 1.337, 
                    combined_required_margin = 1.337, 
                    combined_final_margin = 1.337, 
                    available_margin = 1.337, ),
                msg = ''
            )
        else:
            return GetBasketOrderMargin200Response(
        )
        """

    def testGetBasketOrderMargin200Response(self):
        """Test GetBasketOrderMargin200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
