# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_order_history200_response import GetOrderHistory200Response

class TestGetOrderHistory200Response(unittest.TestCase):
    """GetOrderHistory200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrderHistory200Response:
        """Test GetOrderHistory200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrderHistory200Response`
        """
        model = GetOrderHistory200Response()
        if include_optional:
            return GetOrderHistory200Response(
                s = '',
                d = openapi_client.models.order_history_data.OrderHistoryData(
                    order_id = '', 
                    status = 'open', 
                    reason = '', 
                    avg_price = 1.337, 
                    total_fill_qty = 1.337, 
                    remarks = '', 
                    history = [
                        openapi_client.models.order_log.OrderLog(
                            msg = '', 
                            fill_id = '', 
                            fill_price = 1.337, 
                            fill_qty = 1.337, 
                            time = '', )
                        ], ),
                msg = ''
            )
        else:
            return GetOrderHistory200Response(
        )
        """

    def testGetOrderHistory200Response(self):
        """Test GetOrderHistory200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
