# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.sip_order_record import SipOrderRecord

class TestSipOrderRecord(unittest.TestCase):
    """SipOrderRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SipOrderRecord:
        """Test SipOrderRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SipOrderRecord`
        """
        model = SipOrderRecord()
        if include_optional:
            return SipOrderRecord(
                sip_name = '',
                status = '',
                sip_type = 'daily',
                modify_start_date = True,
                registered_date = '',
                start_date = '',
                due_date = '',
                last_executed_date = '',
                execution_date = '',
                sip_id = '',
                pending_period = 1.337,
                period = 1.337,
                executed_period = 1.337,
                schedule_desc = '',
                symbols = [
                    openapi_client.models.scrip_info.ScripInfo(
                        sym_id = 'EQT_RELIANCE_EQ_NSE', 
                        invest_by = 'qty', 
                        qty = 10, 
                        amount = 50000, )
                    ]
            )
        else:
            return SipOrderRecord(
                sip_type = 'daily',
        )
        """

    def testSipOrderRecord(self):
        """Test SipOrderRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
