# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.funds_api import FundsApi


class TestFundsApi(unittest.TestCase):
    """FundsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FundsApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_funds_limits(self) -> None:
        """Test case for retrieve_funds_limits

        Limits
        """
        pass


if __name__ == '__main__':
    unittest.main()
