# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.basket_order_margin_request import BasketOrderMarginRequest

class TestBasketOrderMarginRequest(unittest.TestCase):
    """BasketOrderMarginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasketOrderMarginRequest:
        """Test BasketOrderMarginRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BasketOrderMarginRequest`
        """
        model = BasketOrderMarginRequest()
        if include_optional:
            return BasketOrderMarginRequest(
                basket_orders = [
                    openapi_client.models.basket_order_list.BasketOrderList(
                        sym_id = 'EQT_RELIANCE_EQ_NSE', 
                        qty = 1, 
                        limit_price = 1.337, 
                        side = 'buy', 
                        type = 'limit', 
                        product = 'delivery', 
                        trig_price = 1.337, )
                    ]
            )
        else:
            return BasketOrderMarginRequest(
        )
        """

    def testBasketOrderMarginRequest(self):
        """Test BasketOrderMarginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
