# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.chart_data_api import ChartDataApi


class TestChartDataApi(unittest.TestCase):
    """ChartDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChartDataApi()

    def tearDown(self) -> None:
        pass

    def test_get_interval_chart_data(self) -> None:
        """Test case for get_interval_chart_data

        Interval Chart
        """
        pass


if __name__ == '__main__':
    unittest.main()
