# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.symbol_details_api import SymbolDetailsApi


class TestSymbolDetailsApi(unittest.TestCase):
    """SymbolDetailsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SymbolDetailsApi()

    def tearDown(self) -> None:
        pass

    def test_get_symbol_details(self) -> None:
        """Test case for get_symbol_details

        Scrip Master Data
        """
        pass

    def test_version_details(self) -> None:
        """Test case for version_details

        Scrip Master Groups
        """
        pass


if __name__ == '__main__':
    unittest.main()
