# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.pending_gtt_order_data import PendingGTTOrderData

class TestPendingGTTOrderData(unittest.TestCase):
    """PendingGTTOrderData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PendingGTTOrderData:
        """Test PendingGTTOrderData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PendingGTTOrderData`
        """
        model = PendingGTTOrderData()
        if include_optional:
            return PendingGTTOrderData(
                sym_id = '',
                exchange = '',
                order_id = '',
                side = '',
                trigger_type = 'Single',
                single = openapi_client.models.place_order_params_data.PlaceOrderParamsData(
                    remarks = '', 
                    trig_price = 1.337, 
                    product = 'delivery', 
                    type = 'limit', 
                    qty = 1.337, 
                    price = 1.337, ),
                stop_loss = openapi_client.models.place_order_params_data.PlaceOrderParamsData(
                    remarks = '', 
                    trig_price = 1.337, 
                    product = 'delivery', 
                    type = 'limit', 
                    qty = 1.337, 
                    price = 1.337, ),
                target = openapi_client.models.place_order_params_data.PlaceOrderParamsData(
                    remarks = '', 
                    trig_price = 1.337, 
                    product = 'delivery', 
                    type = 'limit', 
                    qty = 1.337, 
                    price = 1.337, )
            )
        else:
            return PendingGTTOrderData(
        )
        """

    def testPendingGTTOrderData(self):
        """Test PendingGTTOrderData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
