# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.brokerage_data import BrokerageData

class TestBrokerageData(unittest.TestCase):
    """BrokerageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrokerageData:
        """Test BrokerageData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrokerageData`
        """
        model = BrokerageData()
        if include_optional:
            return BrokerageData(
                charges = 1.337,
                detailed_view = [
                    openapi_client.models.values.Values(
                        key = '', 
                        value = 1.337, )
                    ]
            )
        else:
            return BrokerageData(
        )
        """

    def testBrokerageData(self):
        """Test BrokerageData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
