# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.holding_response import HoldingResponse

class TestHoldingResponse(unittest.TestCase):
    """HoldingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HoldingResponse:
        """Test HoldingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HoldingResponse`
        """
        model = HoldingResponse()
        if include_optional:
            return HoldingResponse(
                s = 'ok',
                d = openapi_client.models.holding_data.HoldingData(
                    holdings = [
                        openapi_client.models.holdings.Holdings(
                            sym_id = '', 
                            sym = {
                                'key' : None
                                }, 
                            qty = 1.337, 
                            avg_price = 1.337, 
                            t1_qty = 1.337, 
                            saleable_qty = 1.337, 
                            pledge_qty = 1.337, 
                            non_poa_qty = 1.337, 
                            dp_qty = 1.337, 
                            ben_qty = 1.337, 
                            unpledged_qty = 1.337, 
                            broker_col_qty = 1.337, 
                            btst_colqty = 1.337, 
                            used_qty = 1.337, 
                            traded_qty = 1.337, 
                            realized_pnl = 1.337, 
                            total_qty = 1.337, 
                            trans_history = True, 
                            day_qty = 1.337, )
                        ], 
                    has_non_poa_record = True, )
            )
        else:
            return HoldingResponse(
        )
        """

    def testHoldingResponse(self):
        """Test HoldingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
