# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.exit_order200_response import ExitOrder200Response

class TestExitOrder200Response(unittest.TestCase):
    """ExitOrder200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExitOrder200Response:
        """Test ExitOrder200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExitOrder200Response`
        """
        model = ExitOrder200Response()
        if include_optional:
            return ExitOrder200Response(
                s = '',
                d = openapi_client.models.exit_sno_data.ExitSnoData(
                    msg = '', ),
                msg = ''
            )
        else:
            return ExitOrder200Response(
        )
        """

    def testExitOrder200Response(self):
        """Test ExitOrder200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
