# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.get_user_details200_response import GetUserDetails200Response

class TestGetUserDetails200Response(unittest.TestCase):
    """GetUserDetails200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserDetails200Response:
        """Test GetUserDetails200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserDetails200Response`
        """
        model = GetUserDetails200Response()
        if include_optional:
            return GetUserDetails200Response(
                s = '',
                d = openapi_client.models.client_details_data.ClientDetailsData(
                    user_id = '', 
                    user_name = '', 
                    mobile = '', 
                    email = '', 
                    pan = '', 
                    dp_id = '', 
                    bank_details = [
                        openapi_client.models.bank_dtls.BankDtls(
                            bank_name = '', 
                            acc_no = '', 
                            ifsc = '', )
                        ], 
                    dp_ids = [
                        ''
                        ], 
                    products = [
                        ''
                        ], 
                    segments = [
                        ''
                        ], ),
                msg = ''
            )
        else:
            return GetUserDetails200Response(
        )
        """

    def testGetUserDetails200Response(self):
        """Test GetUserDetails200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
