# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.client_details_response import ClientDetailsResponse

class TestClientDetailsResponse(unittest.TestCase):
    """ClientDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientDetailsResponse:
        """Test ClientDetailsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientDetailsResponse`
        """
        model = ClientDetailsResponse()
        if include_optional:
            return ClientDetailsResponse(
                s = 'ok',
                d = openapi_client.models.client_details_data.ClientDetailsData(
                    user_id = '', 
                    user_name = '', 
                    mobile = '', 
                    email = '', 
                    pan = '', 
                    dp_id = '', 
                    bank_details = [
                        openapi_client.models.bank_dtls.BankDtls(
                            bank_name = '', 
                            acc_no = '', 
                            ifsc = '', )
                        ], 
                    dp_ids = [
                        ''
                        ], 
                    products = [
                        ''
                        ], 
                    segments = [
                        ''
                        ], )
            )
        else:
            return ClientDetailsResponse(
        )
        """

    def testClientDetailsResponse(self):
        """Test ClientDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
