# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.cancel_order_response import CancelOrderResponse

class TestCancelOrderResponse(unittest.TestCase):
    """CancelOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CancelOrderResponse:
        """Test CancelOrderResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CancelOrderResponse`
        """
        model = CancelOrderResponse()
        if include_optional:
            return CancelOrderResponse(
                s = 'ok',
                d = openapi_client.models.cancel_order_data.CancelOrderData(
                    msg = '', 
                    order_id = '', )
            )
        else:
            return CancelOrderResponse(
        )
        """

    def testCancelOrderResponse(self):
        """Test CancelOrderResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
