# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.order_history_data import OrderHistoryData

class TestOrderHistoryData(unittest.TestCase):
    """OrderHistoryData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderHistoryData:
        """Test OrderHistoryData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderHistoryData`
        """
        model = OrderHistoryData()
        if include_optional:
            return OrderHistoryData(
                order_id = '',
                status = 'open',
                reason = '',
                avg_price = 1.337,
                total_fill_qty = 1.337,
                remarks = '',
                history = [
                    openapi_client.models.order_log.OrderLog(
                        msg = '', 
                        fill_id = '', 
                        fill_price = 1.337, 
                        fill_qty = 1.337, 
                        time = '', )
                    ]
            )
        else:
            return OrderHistoryData(
        )
        """

    def testOrderHistoryData(self):
        """Test OrderHistoryData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
