# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.basket_order_list import BasketOrderList

class TestBasketOrderList(unittest.TestCase):
    """BasketOrderList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BasketOrderList:
        """Test BasketOrderList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BasketOrderList`
        """
        model = BasketOrderList()
        if include_optional:
            return BasketOrderList(
                sym_id = 'EQT_RELIANCE_EQ_NSE',
                qty = 1,
                limit_price = 1.337,
                side = 'buy',
                type = 'limit',
                product = 'delivery',
                trig_price = 1.337
            )
        else:
            return BasketOrderList(
                sym_id = 'EQT_RELIANCE_EQ_NSE',
                qty = 1,
                side = 'buy',
                type = 'limit',
                product = 'delivery',
        )
        """

    def testBasketOrderList(self):
        """Test BasketOrderList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
