# coding: utf-8

"""
    CubePlus Rest API Specifications

    Gateway API's

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.day_position import DayPosition

class TestDayPosition(unittest.TestCase):
    """DayPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayPosition:
        """Test DayPosition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DayPosition`
        """
        model = DayPosition()
        if include_optional:
            return DayPosition(
                day_qty = 1.337,
                day_avg = 1.337,
                day_realized_pnl = 1.337,
                day_net_value = 1.337,
                convert_pos = True,
                day_premium = 1.337
            )
        else:
            return DayPosition(
        )
        """

    def testDayPosition(self):
        """Test DayPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
